# Generated by Django 5.1.4 on 2024-12-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_com', '0002_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Users')], default=1),
        ),
    ]
