# Generated by Django 5.1.4 on 2025-01-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_com', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
