# Generated by Django 5.1.4 on 2025-01-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_com', '0005_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
