# Generated by Django 5.1.4 on 2025-01-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_com', '0006_users_fname_users_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lname',
        ),
    ]
