# Generated by Django 5.1.4 on 2025-02-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_com', '0009_order_payment_status_alter_orderdetails_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='item_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
