# Generated by Django 5.1.4 on 2025-02-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_com', '0010_orderdetails_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Users')], default=2),
        ),
    ]
